#!/bin/bash

# Update system
sudo yum update -y   # For Amazon Linux

# Install Node.js
curl -fsSL https://rpm.nodesource.com/setup_lts.x | sudo bash -
sudo yum install -y nodejs   # For Amazon Linux

# Install Git
sudo yum install -y git   # For Amazon Linux

# Install PM2 globally
sudo npm install pm2 -g

# Create app directory
mkdir /home/ec2-user/app
cd /home/ec2-user/app

# Clone your repository
git clone https://github.com/fuhuan1991/Reversi-AI-Game.git .

# Install dependencies
npm install

# Start application with PM2
pm2 start npm --name "reversi" -- run prod --log /var/log/reversi.log

# Save PM2 process list and configure to start on system boot
pm2 save
pm2 startup